name: Build odysseyn1x

on:
  push:
    paths:
      - 'build.sh'

jobs:

  build:

    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        dnf update -y
        dnf install -y wget rpm-build dnf-plugins-core grub2-pc-modules grub2-efi-x64-modules \
          squashfs-tools xorriso ca-certificates curl libusbx-devel gcc make gzip xz \
          unzip glibc-devel git

    - name: Build for amd64
      run: |
        sed -i "/Exit if user isn't root/aVERSION='$(cat version)'" build.sh
        sed -i "/Exit if user isn't root/aARCH='amd64'" build.sh
        chmod +x build.sh
        ./build.sh

    - name: Build for i686
      run: |
        dnf install -y glibc-devel.i686 libusbx-devel.i686 gcc-c++.i686
        sed -i "s/ARCH='amd64'/ARCH='i686'/g" build.sh
        chmod +x build.sh
        ./build.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: odysseyn1x-iso
        path: odysseyn1x-*.iso
